import {initial,transition,type Mode} from '../lib/demo-state';
const demo=document.querySelector<HTMLElement>('#island-demo');
if(demo){
 const q=<T extends HTMLElement=HTMLElement>(s:string)=>demo.querySelector<T>(s)!;
 const all=(s:string)=>demo.querySelectorAll<HTMLButtonElement>(s);
 let state=initial(),leave:ReturnType<typeof setTimeout>|undefined,noticeTimer:ReturnType<typeof setTimeout>|undefined;
 let alert='',notice='',clockMode='timer',running=false,started=0,elapsed=0,durationMs=10000,lapCount=0,ticker:ReturnType<typeof setInterval>|undefined;
 let showCalls=true,callMuted=false,inside=false,hasMedia=false;const now=new Date();let year=now.getFullYear(),month=now.getMonth(),day=now.getDate();
 const names=['A slower morning','Room to breathe','One small moment'];const panels:Mode[]=['music','files','controls','clock','calendar','call','settings'];
 const hints:Record<Mode,string>={idle:'Quiet until you need it. Choose Music to start the sample.',peek:'Click to open. Music controls appear when media is active.',music:'Artwork, playback and your day. Together.',files:'A stop along the way. Originals stay put.',controls:'Small adjustments, right within reach.',clock:'Time moves. Your island moves with it.',calendar:'Your calendars, in one little space.',call:'One mute button. A quieter call display.',settings:'A little more you.'};
 const announce=(s:string)=>q('#demo-status').textContent=s;
 const format=(ms:number)=>{const sec=Math.floor(Math.max(0,ms)/1000);return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')};
 const precise=(ms:number)=>format(ms)+'.'+String(Math.floor(Math.max(0,ms)%1000/10)).padStart(2,'0');
 function clockValue(){return elapsed+(running?Date.now()-started:0)}
 function paintClock(){const value=clockValue(),limit=clockMode==='alarm'?10000:durationMs;demo!.dataset.clockMode=clockMode;q('#clock-readout').textContent=alert?'Time is up':clockMode==='stopwatch'?precise(value):format(limit-value);q('#compact-clock').textContent=alert?'Alert':format(clockMode==='stopwatch'?value:limit-value);q('#clock-caption').textContent=alert?'Stays until you press Dismiss':clockMode==='stopwatch'?'Hundredths while running · Lap records a split':clockMode==='alarm'?'Sample alarm after ten seconds':`${durationMs/1000}-second sample timer`;q('#clock-start').textContent=running?'Pause':elapsed?'Resume':clockMode==='stopwatch'?'Start stopwatch':clockMode==='alarm'?'Set sample alarm':'Start timer';q('#dismiss-alert').hidden=!alert;q('.clock-actions').hidden=!!alert;q('#clock-lap').hidden=clockMode!=='stopwatch'||!running;q('.clock-ring').style.setProperty('--progress',String(Math.min(1,value/limit)*360)+'deg');q('.timer-scale').style.setProperty('--duration-percent',String(durationMs/300)+'%');q('.stopwatch-dial').style.setProperty('--seconds-deg',String(value%60000/60000*360)+'deg');}
 function render(){demo!.dataset.mode=state.mode;demo!.dataset.playing=String(state.playing);demo!.dataset.media=String(hasMedia);demo!.dataset.alert=String(!!alert);demo!.dataset.notice=String(!!notice);demo!.dataset.clockActive=String(running||elapsed>0||!!alert);q('.capsule-inner').inert=['idle','peek'].includes(state.mode)||!!notice||demo!.dataset.minimized==='true';q('.peek-transport').inert=state.mode!=='peek'||!hasMedia||!!notice||demo!.dataset.minimized==='true';q('.compact-content').setAttribute('aria-hidden',String(!hasMedia&&!running&&!elapsed&&!alert));panels.forEach(p=>q('#demo-'+p).hidden=state.mode!==p);all('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));q('#pin-demo').setAttribute('aria-pressed',String(state.pinned));q('#sample-card').hidden=state.mode!=='files';q('#stage-hint').textContent=hints[state.mode];q('#stage-count').textContent=String(Math.max(0,panels.indexOf(state.mode)+1)+1).padStart(2,'0')+' / 08';q('.notice-card').hidden=!notice;q('#compact-clock').hidden=!(running||elapsed>0||alert);q('#track-name').textContent=names[state.track];q('#compact-title').textContent=alert?'Open Clock to dismiss':running||elapsed?(clockMode==='stopwatch'?'Stopwatch':clockMode==='alarm'?'Alarm':'Timer'):names[state.track];demo!.style.setProperty('--art-hue',String(state.track*65)+'deg');all('[data-transport="play"]').forEach(b=>{b.textContent=state.playing?'Ⅱ':'▶';b.setAttribute('aria-label',state.playing?'Pause sample track':'Play sample track')});paintClock();}
 function select(mode:Mode){delete demo!.dataset.minimized;clearTimeout(leave);inside=false;if(mode==='call'&&!showCalls){announce('Show calls is off. Enable it in Settings to preview calls.');mode='settings'}clearTimeout(noticeTimer);notice='';state=transition(state,'mode',mode);if(mode==='music'){state.playing=true;hasMedia=true;}render();announce(hints[mode]);}
 function pop(kind:string){delete demo!.dataset.minimized;if(alert&&kind!=='timer'&&kind!=='alarm'){select('clock');announce('Dismiss the clock alert before previewing another notification.');return}clearTimeout(noticeTimer);notice=kind;if(kind==='timer'||kind==='alarm'){alert=kind;running=false;stopTick();clockMode=kind==='alarm'?'alarm':'timer'}q('#notice-title').textContent=kind==='image'?'Image copied':kind==='calendar'?'Design catch-up':kind==='alarm'?'Alarm ringing':'Timer complete';q('#notice-subtitle').textContent=kind==='calendar'?'Starts in 5 minutes · Work':kind==='image'?'Ready for your tray':'Open Clock to dismiss';q('.notice-symbol').textContent=kind==='image'?'▣':kind==='calendar'?'▦':'';demo!.dataset.noticeKind=kind;render();announce(q('#notice-title').textContent!);noticeTimer=setTimeout(()=>{notice='';state={...state,mode:'idle'};render()},3200);}
 function stopTick(){clearInterval(ticker);ticker=undefined}
 function tick(){const limit=clockMode==='alarm'?10000:durationMs;if(running&&clockMode!=='stopwatch'&&clockValue()>=limit){elapsed=limit;pop(clockMode==='alarm'?'alarm':'timer')}else paintClock()}
 function startTick(){stopTick();if(running&&!document.hidden)ticker=setInterval(tick,clockMode==='stopwatch'?50:250)}
 const spotifyMark=q('.spotify-badge').innerHTML;
 all('[data-provider]').forEach(b=>b.onclick=e=>{e.stopPropagation();const provider=b.dataset.provider!;all('[data-provider]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));q('.spotify-label').textContent=provider+' · sample';demo!.dataset.provider=provider;demo!.querySelectorAll<HTMLElement>('.spotify-badge').forEach(badge=>{if(provider==='Spotify')badge.innerHTML=spotifyMark;else {badge.replaceChildren();badge.textContent=provider==='Apple Music'?'♫':'▶'}});announce(provider+' sample selected. Artwork stays primary. No account is connected.')});
 all('[data-mode]').forEach(b=>b.onclick=e=>{e.stopPropagation();select(b.dataset.mode as Mode);inside=!!b.closest('.capsule')});
 q('#capsule').onpointerenter=()=>{if(demo!.dataset.minimized==='true')return;inside=true;clearTimeout(leave);if(!notice){state=transition(state,'hover');render()}};
 q('#capsule').onpointerleave=()=>{if(!inside)return;inside=false;leave=setTimeout(()=>{state=transition(state,'leave');render()},300)};
 q('#capsule').onclick=e=>{if((e.target as HTMLElement).closest('button,input,label'))return;if(notice){const was=notice;select(alert?'clock':was==='calendar'?'calendar':'files');return}if(state.mode==='idle'||state.mode==='peek')select(alert||running||elapsed?'clock':'music')};
 q('#capsule').onkeydown=e=>{if(e.target===q('#capsule')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();select(alert||running||elapsed?'clock':'music')}};
 demo.onkeydown=e=>{if(e.key==='Escape'){clearTimeout(noticeTimer);notice='';state=transition(state,'escape');render();q('#capsule').focus();announce(alert?'Collapsed. Clock alert remains active.':'Preview collapsed.')}};
 q('#pin-demo').onclick=()=>{state=transition(state,'pin');render()};
 all('[data-transport]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.dataset.transport==='play')state.playing=!state.playing;else state.track=(state.track+(b.dataset.transport==='next'?1:2))%3;render();announce('Sample playback updated. No audio plays.')});
 function drawFiles(){q('#sample-files').replaceChildren();for(const name of state.files){const li=document.createElement('li'),text=document.createElement('span'),remove=document.createElement('button');text.textContent='▤ '+name;remove.textContent='×';remove.setAttribute('aria-label','Remove '+name);remove.onclick=()=>{state.files=state.files.filter(f=>f!==name);drawFiles();announce('Sample reference removed. Originals stay put.')};li.append(text,remove);q('#sample-files').append(li)}}
 function addFile(screenshot=false){const options=screenshot?['Screenshot 01.png','Screenshot 02.png','Screenshot 03.png']:['Weekend notes.txt','Project outline.pdf','Ideas.png'];const name=options.find(f=>!state.files.includes(f));if(name&&state.files.length<6){state.files.push(name);drawFiles();announce('Sample reference added. No real file was accessed.')}else announce('Remove a sample reference to make room.')}
 q('#add-file').onclick=()=>addFile();q('#sample-screenshot').onclick=()=>addFile(true);q('#sample-card').onclick=()=>addFile();q('#sample-card').ondragstart=e=>e.dataTransfer?.setData('application/x-floatlet-sample','sample');q('#capsule').ondragover=e=>e.preventDefault();q('#capsule').ondrop=e=>{e.preventDefault();if(state.mode==='files'&&e.dataTransfer?.getData('application/x-floatlet-sample')==='sample')addFile();else announce('Use sample files. Real files are not read or uploaded.')};
 const rejectFiles=(e:DragEvent)=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault()};window.addEventListener('dragover',rejectFiles);window.addEventListener('drop',rejectFiles);
 for(const id of ['volume','brightness'])q<HTMLInputElement>('#'+id).oninput=()=>{const value=q<HTMLInputElement>('#'+id).value;q('#'+id+'-value').textContent=value+'%';if(id==='volume')q('#mute').setAttribute('aria-pressed',String(value==='0'))};let volume=42;q('#mute').onclick=()=>{const v=q<HTMLInputElement>('#volume');if(+v.value){volume=+v.value;v.value='0'}else v.value=String(volume);v.dispatchEvent(new Event('input'))};
 all('[data-native]').forEach(b=>b.onclick=()=>announce(b.dataset.native==='Wi-Fi'?'The app lists nearby networks and connects using saved profiles. This sample does not scan your network.':`${b.dataset.native} opens Windows controls in the app. This preview does not change your computer.`));
 all('[data-clock]').forEach(b=>b.onclick=()=>{if(alert){announce('Dismiss the active alert first.');return}running=false;elapsed=0;lapCount=0;q('#clock-lap-summary').hidden=true;stopTick();clockMode=b.dataset.clock!;all('[data-clock]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});
 q<HTMLInputElement>('#timer-duration').oninput=e=>{if(running||elapsed)return;durationMs=Number((e.target as HTMLInputElement).value)*1000;render()};
 q('#clock-start').onclick=()=>{if(running){elapsed=clockValue();running=false}else {started=Date.now();running=true}startTick();render()};q('#clock-reset').onclick=()=>{if(alert)return;running=false;elapsed=0;lapCount=0;q('#clock-lap-summary').hidden=true;stopTick();render()};q('#clock-lap').onclick=()=>{lapCount++;const summary=q('#clock-lap-summary');summary.textContent=`Lap ${lapCount} · ${precise(clockValue())}`;summary.hidden=false;announce(summary.textContent)};q('#dismiss-alert').onclick=()=>{alert='';notice='';elapsed=0;running=false;clearTimeout(noticeTimer);render();announce('Clock alert dismissed.')};
 function drawCalendar(){q('#calendar-month').textContent=new Date(year,month,1).toLocaleDateString('en-GB',{month:'long',year:'numeric'});const grid=q('#calendar-grid');grid.replaceChildren();const offset=(new Date(year,month,1).getDay()+6)%7;for(let i=0;i<offset;i++)grid.append(document.createElement('span'));const count=new Date(year,month+1,0).getDate();day=Math.min(day,count);for(let d=1;d<=count;d++){const b=document.createElement('button');b.textContent=String(d);b.setAttribute('aria-label',new Date(year,month,d).toLocaleDateString('en-GB',{dateStyle:'full'}));b.setAttribute('aria-pressed',String(day===d));if(d%3===0||d===now.getDate())b.className='has-event';b.onclick=()=>{day=d;drawCalendar()};grid.append(b)}q('#day-agenda').replaceChildren();const title=document.createElement('strong');title.textContent=new Date(year,month,day).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});const event=document.createElement('p');event.textContent=(day%3===0||day===now.getDate())?'09:30  Morning walk · Personal / 14:00  Design catch-up · Work':'No sample events. A little room to breathe.';q('#day-agenda').append(title,event)}
 q('#calendar-prev').onclick=()=>{if(--month<0){month=11;year--}drawCalendar()};q('#calendar-next').onclick=()=>{if(++month>11){month=0;year++}drawCalendar()};q('#calendar-reminder').onclick=()=>pop('calendar');q('#music-month').textContent=now.toLocaleDateString('en-GB',{month:'short'}).toUpperCase();q('#music-day').textContent=String(now.getDate());
 all('[data-notice]').forEach(b=>b.onclick=()=>pop(b.dataset.notice!));
 q('#call-mute').onclick=()=>{callMuted=!callMuted;q('#call-mute').textContent=callMuted?'Unmute microphone':'Mute microphone';q('#call-mute').setAttribute('aria-pressed',String(callMuted));announce('Sample microphone '+(callMuted?'muted':'unmuted')+'. Your microphone is unchanged.')};q('#call-open').onclick=()=>announce('The Windows app brings your call app forward. This preview does not launch Discord.');
 q<HTMLInputElement>('#show-calls').onchange=e=>{showCalls=(e.target as HTMLInputElement).checked;announce(showCalls?'Call preview enabled.':'Show calls off. The app hides activity and stops microphone monitoring.')};q<HTMLInputElement>('#icon-only').onchange=e=>demo!.dataset.iconOnly=String((e.target as HTMLInputElement).checked);q<HTMLInputElement>('#reduce-motion').onchange=e=>demo!.dataset.reduced=String((e.target as HTMLInputElement).checked);
 q('#reset-demo').onclick=()=>{delete demo!.dataset.minimized;all('[data-provider]')[0].click();stopTick();clearTimeout(leave);clearTimeout(noticeTimer);state=initial();hasMedia=false;notice=alert='';clockMode='timer';running=false;elapsed=0;durationMs=10000;lapCount=0;q<HTMLInputElement>('#timer-duration').value='10';q('#clock-lap-summary').hidden=true;callMuted=false;showCalls=true;day=now.getDate();month=now.getMonth();year=now.getFullYear();for(const id of ['icon-only','reduce-motion','show-calls'])q<HTMLInputElement>('#'+id).checked=id==='show-calls';demo!.dataset.iconOnly='false';demo!.dataset.reduced='false';q('#call-mute').textContent='Mute microphone';q('#call-mute').setAttribute('aria-pressed','false');all('[data-clock]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.clock==='timer')));for(const [id,v] of [['volume','42'],['brightness','70']]){q<HTMLInputElement>('#'+id).value=v;q('#'+id).dispatchEvent(new Event('input'))}drawFiles();drawCalendar();render();announce('Preview reset.')};
 document.querySelectorAll<HTMLButtonElement>('[data-chapter]').forEach(b=>b.onclick=()=>{select(b.dataset.chapter as Mode);demo!.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});q('#capsule').focus({preventScroll:true})});
 new IntersectionObserver(([entry])=>{demo!.dataset.offscreen=String(!entry.isIntersecting)}).observe(demo);
 document.addEventListener('visibilitychange',()=>{demo!.dataset.hidden=String(document.hidden);if(document.hidden){stopTick();clearTimeout(leave)}else{tick();startTick()}});drawCalendar();drawFiles();render();
}

const playground=document.querySelector<HTMLElement>('#island-demo');
const minimize=document.querySelector<HTMLButtonElement>('#minimize-demo');
const restore=document.querySelector<HTMLButtonElement>('#restore-demo');
if(playground&&minimize&&restore){minimize.onclick=e=>{e.stopPropagation();playground.dataset.minimized='true';(playground.querySelector('.capsule-inner') as HTMLElement).inert=true;(playground.querySelector('.peek-transport') as HTMLElement).inert=true;restore.focus()};restore.onclick=e=>{e.stopPropagation();delete playground.dataset.minimized;(playground.querySelector('.capsule-inner') as HTMLElement).inert=['idle','peek'].includes(playground.dataset.mode||'idle');(playground.querySelector('.peek-transport') as HTMLElement).inert=playground.dataset.mode!=='peek';minimize.focus()};}
const searchDialog=document.querySelector<HTMLDialogElement>('#search-dialog');
const searchInput=document.querySelector<HTMLInputElement>('#search-sample-input');
const searchResults=document.querySelector<HTMLUListElement>('#search-sample-results');
const searchIcons={app:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><rect x="3" y="4" width="18" height="16" rx="3"/><path d="M3 9h18M8 6.5h.01"/></svg>',file:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h4M9 12h6M9 16h6"/></svg>',folder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10H3z"/></svg>',clock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></svg>',calendar:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4M7 14h2M12 14h2M16 14h2"/></svg>',music:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M9 18V5l11-2v13M9 7l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/></svg>'};
const samples=[{name:'Google Chrome',kind:'Application',icon:searchIcons.app},{name:'Notepad',kind:'Application',icon:searchIcons.app},{name:'Calendar',kind:'Floatlet command',icon:searchIcons.calendar},{name:'Music',kind:'Floatlet command',icon:searchIcons.music},{name:'Google',kind:'Sample folder',icon:searchIcons.folder},{name:'Weekend notes.txt',kind:'Sample file',icon:searchIcons.file}];
if(searchDialog&&searchInput&&searchResults){
 let selected=0;let matches=samples;let soundOn=true;let audio:AudioContext|undefined;
 const status=document.querySelector<HTMLElement>('#search-sample-status')!;
 const soundButton=document.querySelector<HTMLButtonElement>('#search-sound')!;
 const openingSound=()=>{if(!soundOn)return;try{audio??=new AudioContext();if(audio.state==='suspended')void audio.resume();const start=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(620,start);osc.frequency.exponentialRampToValueAtTime(940,start+.075);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.026,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+.12);osc.connect(gain).connect(audio.destination);osc.start(start);osc.stop(start+.13)}catch{}}
 const activate=(name:string)=>{status.textContent=name+' selected. In the desktop build, Enter opens this result. This is sample data.'};
 const rows=samples.map(x=>{const row=document.createElement('li'),button=document.createElement('button'),icon=document.createElement('span'),copy=document.createElement('span'),name=document.createElement('strong'),detail=document.createElement('small'),arrow=document.createElement('span');icon.className='result-icon';icon.innerHTML=x.icon;name.textContent=x.name;detail.textContent=x.kind;copy.append(name,detail);arrow.textContent='↵';arrow.className='result-enter';button.append(icon,copy,arrow);button.onclick=()=>activate(x.name);row.append(button);return row});searchResults.append(...rows);
 const highlight=()=>rows.forEach((row,i)=>{const b=row.firstElementChild as HTMLButtonElement;const matchIndex=matches.indexOf(samples[i]);const active=matchIndex>=0&&matchIndex===selected;b.dataset.selected=String(active);b.setAttribute('aria-current',String(active))});
 const draw=()=>{const query=searchInput.value.trim().toLowerCase();matches=samples.filter(x=>x.name.toLowerCase().includes(query));rows.forEach((row,i)=>row.hidden=!matches.includes(samples[i]));selected=0;highlight();status.textContent=matches.length?matches.length+' sample results. Use the arrow keys and Enter.':'No sample matches. Try Google, Notepad or Calendar.'};
 soundButton.onclick=()=>{soundOn=!soundOn;soundButton.textContent=soundOn?'Sound on':'Sound off';soundButton.setAttribute('aria-pressed',String(soundOn));soundButton.setAttribute('aria-label',soundOn?'Turn search sound off':'Turn search sound on')};
 document.querySelectorAll<HTMLButtonElement>('[data-search-open]').forEach(b=>b.onclick=()=>{if(!searchDialog.open){searchDialog.showModal();openingSound()}searchInput.value='';draw();searchInput.focus()});
 searchInput.oninput=draw;searchInput.onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();selected=Math.max(0,Math.min(matches.length-1,selected+(e.key==='ArrowDown'?1:-1)));highlight();if(matches[selected])rows[samples.indexOf(matches[selected])].scrollIntoView({block:'nearest'});}if(e.key==='Enter'&&matches[selected]){e.preventDefault();activate(matches[selected].name)}};
}
