import {readConsent,denied,cleanEvent,type Consent} from '../lib/policy';
declare global{interface Window{dataLayer?:unknown[];gtag?:(...args:unknown[])=>void;clarity?:((...args:unknown[])=>void)&{q?:unknown[][]}}}
const key='floatlet-privacy';let choice:Consent|null=null;try{choice=readConsent(localStorage.getItem(key))}catch{}let active=choice||denied();let gaLoaded=false,replayLoaded=false;const ga=import.meta.env.PUBLIC_GA4_ID||'';const clarity=import.meta.env.PUBLIC_CLARITY_ID||'';const enabled=import.meta.env.PUBLIC_TRACKING_ENABLED==='true'&&import.meta.env.MODE==='production';
const addScript=(url:string)=>{const s=document.createElement('script');s.src=url;s.async=true;document.head.append(s)};
function load(){if(!enabled)return;if(active.analytics&&!gaLoaded&&/^G-[A-Z0-9]+$/.test(ga)){gaLoaded=true;window.dataLayer=[];window.gtag=function(){window.dataLayer!.push(arguments)};window.gtag('consent','default',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});window.gtag('consent','update',{analytics_storage:'granted'});window.gtag('js',new Date());window.gtag('config',ga,{send_page_view:false,allow_google_signals:false,allow_ad_personalization_signals:false,page_location:location.origin+location.pathname,page_referrer:''});addScript('https://www.googletagmanager.com/gtag/js?id='+ga)}if(active.replay&&!replayLoaded&&/^[a-z0-9]+$/.test(clarity)){replayLoaded=true;const fn=((...args:unknown[])=>{fn.q.push(args)}) as ((...args:unknown[])=>void)&{q:unknown[][]};fn.q=[];window.clarity=fn;window.clarity('consentv2',{analytics_Storage:'granted',ad_Storage:'denied'});addScript('https://www.clarity.ms/tag/'+clarity)}}
const dialog=document.querySelector<HTMLDialogElement>('#privacy-dialog')!;const analytics=document.querySelector<HTMLInputElement>('#analytics-choice')!;const replay=document.querySelector<HTMLInputElement>('#replay-choice')!;
document.querySelector('#privacy-open')!.addEventListener('click',()=>{analytics.checked=active.analytics;replay.checked=active.replay;dialog.showModal()});
function save(a:boolean,r:boolean){const withdraw=(gaLoaded&&!a)||(replayLoaded&&!r);active={...denied(),analytics:a,replay:r};try{localStorage.setItem(key,JSON.stringify(active))}catch{}if(withdraw){window.gtag?.('consent','update',{analytics_storage:a?'granted':'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});window.clarity?.('consentv2',{analytics_Storage:r?'granted':'denied',ad_Storage:'denied'});for(const cookie of document.cookie.split(';')){const name=cookie.split('=')[0].trim();if(name==='_ga'||name.startsWith('_ga_')||name==='_clck'||name==='_clsk'){for(const domain of ['',location.hostname,'.'+location.hostname])document.cookie=name+'=; Max-Age=0; path=/;'+(domain?' domain='+domain+';':'')}}location.reload();return}load();dialog.close()}
document.querySelector('#privacy-save')!.addEventListener('click',e=>{e.preventDefault();save(analytics.checked,replay.checked)});document.querySelector('#privacy-reject')!.addEventListener('click',e=>{e.preventDefault();save(false,false)});document.querySelector('#privacy-accept')!.addEventListener('click',e=>{e.preventDefault();save(true,true)});
function event(name:string,params:Record<string,unknown>){const safe=cleanEvent(name,params);if(safe&&enabled&&active.analytics&&gaLoaded)window.gtag?.('event',safe.name,safe.params)}document.addEventListener('floatlet-event',e=>{const v=(e as CustomEvent).detail;if(v)event(v.name,v.params)});document.addEventListener('click',e=>{const target=(e.target as Element).closest<HTMLElement>('[data-event]');if(target)event(target.dataset.event!,{placement:target.dataset.placement||'body',architecture:'x64',version:'0.6.3',package_type:'exe'})});load();
if(enabled&&!choice)dialog.showModal();
