#pragma once
#include "model.h"
#include <shlobj.h>
#include <filesystem>
#include <fstream>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <functional>
#include <chrono>
namespace delight::search {
// Local filename metadata only. Folder names are stored once and shared by children.
class LocalIndex {
    static constexpr uint32_t NoParent=0xffffffffu;
    struct Entry {std::wstring name,lower;uint32_t parent=NoParent;bool directory=false,root=false;};
    struct Snapshot {std::vector<Entry> entries;bool limited=false;unsigned skipped=0;};
    static constexpr size_t Budget=16*1024*1024,Limit=100000;
    std::mutex mutex;std::condition_variable wake;
    std::shared_ptr<const Snapshot> snapshot;std::vector<std::wstring> roots;
    std::filesystem::path cache;std::function<void()> changed;
    std::atomic<unsigned> revision=0;bool stop=false,enabled=false,pending=false,building=false,forced=false;
    ULONGLONG requested=0;std::wstring error;std::thread worker;
    bool current(unsigned r)const{return revision.load()==r;}
    void publish(std::shared_ptr<const Snapshot> data,unsigned r){std::function<void()> callback;{std::lock_guard lock(mutex);if(!current(r))return;snapshot=std::move(data);callback=changed;}if(callback)callback();}
    static bool append(Snapshot& data,std::wstring name,uint32_t parent,bool directory,bool root,size_t& bytes){size_t cost=sizeof(Entry)+2*(name.size()+1)*sizeof(wchar_t);if(data.entries.size()>=Limit||bytes+cost>Budget){data.limited=true;return false;}bytes+=cost;data.entries.push_back({name,fold(name),parent,directory,root});return true;}
    static std::wstring fullPath(const Snapshot& data,uint32_t index){std::vector<uint32_t> chain;for(auto i=index;i!=NoParent;i=data.entries[i].parent)chain.push_back(i);std::wstring path=data.entries[chain.back()].name;for(auto it=chain.rbegin()+1;it!=chain.rend();++it){if(!path.empty()&&path.back()!=L'\\')path+=L'\\';path+=data.entries[*it].name;}return path;}
    std::shared_ptr<Snapshot> read(const std::filesystem::path& file,unsigned r){auto data=std::make_shared<Snapshot>();std::error_code ec;if(std::filesystem::file_size(file,ec)>Budget||ec)return data;std::ifstream in(file,std::ios::binary);uint32_t magic=0,count=0;in.read(reinterpret_cast<char*>(&magic),4);in.read(reinterpret_cast<char*>(&count),4);if(magic!=0x464C4933||count>Limit)return data;uint8_t limited=0;uint32_t skipped=0;in.read(reinterpret_cast<char*>(&limited),1);in.read(reinterpret_cast<char*>(&skipped),4);if(!in||limited>1)return data;data->limited=limited!=0;data->skipped=skipped;size_t bytes=0;for(uint32_t i=0;i<count&&current(r);++i){uint32_t n=0,parent=NoParent;uint8_t flags=0;in.read(reinterpret_cast<char*>(&n),4);in.read(reinterpret_cast<char*>(&parent),4);in.read(reinterpret_cast<char*>(&flags),1);if(!in||!n||n>32760||flags>3)return std::make_shared<Snapshot>();std::wstring name(n,L'\0');in.read(reinterpret_cast<char*>(name.data()),n*sizeof(wchar_t));if(!in||name.find(L'\0')!=name.npos)return std::make_shared<Snapshot>();bool root=(flags&2)!=0;if(root?parent!=NoParent||!std::filesystem::path(name).is_absolute():parent>=i||!data->entries[parent].directory||name.find_first_of(L"\\/")!=name.npos||name==L"..")return std::make_shared<Snapshot>();if(!append(*data,std::move(name),parent,(flags&1)!=0,root,bytes))break;}return data;}
    void write(const Snapshot& data,const std::filesystem::path& file,unsigned r){if(file.empty()||!current(r))return;std::error_code ec;std::filesystem::create_directories(file.parent_path(),ec);if(ec)return;auto tmp=file;tmp+=L".tmp";{std::ofstream out(tmp,std::ios::binary|std::ios::trunc);uint32_t magic=0x464C4933,count=uint32_t(data.entries.size());out.write(reinterpret_cast<char*>(&magic),4);out.write(reinterpret_cast<char*>(&count),4);uint8_t limited=data.limited?1:0;out.write(reinterpret_cast<char*>(&limited),1);out.write(reinterpret_cast<const char*>(&data.skipped),4);for(auto& entry:data.entries){if(!current(r))break;uint32_t n=uint32_t(entry.name.size());uint8_t flags=(entry.directory?1:0)|(entry.root?2:0);out.write(reinterpret_cast<char*>(&n),4);out.write(reinterpret_cast<const char*>(&entry.parent),4);out.write(reinterpret_cast<char*>(&flags),1);out.write(reinterpret_cast<const char*>(entry.name.data()),n*sizeof(wchar_t));}out.flush();if(!out)return;}if(current(r))MoveFileExW(tmp.c_str(),file.c_str(),MOVEFILE_REPLACE_EXISTING);else std::filesystem::remove(tmp,ec);}
    struct Watches {std::vector<HANDLE> handles;unsigned version=~0u;~Watches(){clear();}void clear(){for(auto h:handles)FindCloseChangeNotification(h);handles.clear();}bool dirty(){bool result=handles.empty();for(auto h:handles){auto state=WaitForSingleObject(h,0);if(state!=WAIT_TIMEOUT){result=true;FindNextChangeNotification(h);}}return result;}};
    void run(){Watches watches;SetThreadPriority(GetCurrentThread(),THREAD_MODE_BACKGROUND_BEGIN);for(;;){unsigned r;std::vector<std::wstring> locations;std::filesystem::path file;bool load,force;{std::unique_lock lock(mutex);wake.wait(lock,[&]{return stop||pending;});if(stop)break;pending=false;if(!enabled){watches.clear();continue;}r=revision;locations=roots;file=cache;load=!snapshot;force=forced;forced=false;building=true;error.clear();}
        try{bool modified=watches.dirty();if(watches.version!=r){watches.clear();watches.version=r;for(auto& root:locations){auto h=FindFirstChangeNotificationW(root.c_str(),TRUE,FILE_NOTIFY_CHANGE_FILE_NAME|FILE_NOTIFY_CHANGE_DIR_NAME);if(h!=INVALID_HANDLE_VALUE)watches.handles.push_back(h);}modified=true;}if(watches.handles.size()!=locations.size())modified=true;if(!load&&!force&&!modified){std::shared_ptr<const Snapshot> unchanged;{std::lock_guard lock(mutex);if(current(r)){building=false;unchanged=snapshot;}}if(unchanged)publish(unchanged,r);continue;}
            if(load&&!file.empty()){auto saved=read(file,r);if(!saved->entries.empty()){std::error_code ageError;auto modifiedAt=std::filesystem::last_write_time(file,ageError);auto age=std::filesystem::file_time_type::clock::now()-modifiedAt;bool recent=!ageError&&age>=decltype(age)::zero()&&age<std::chrono::minutes(2);publish(saved,r);if(recent&&!force){std::shared_ptr<const Snapshot> currentData;{std::lock_guard lock(mutex);if(current(r)){building=false;currentData=snapshot;}}if(currentData)publish(currentData,r);continue;}}}
            auto data=std::make_shared<Snapshot>();size_t bytes=0,visited=0;for(auto& root:locations){std::error_code ec;if(!append(*data,root,NoParent,true,true,bytes))break;std::vector<uint32_t> parents{uint32_t(data->entries.size()-1)};auto flags=std::filesystem::directory_options::skip_permission_denied;std::filesystem::recursive_directory_iterator it(root,flags,ec),end;if(ec){++data->skipped;continue;}while(it!=end&&current(r)&&!data->limited){auto name=it->path().filename().wstring();auto path=it->path().wstring();DWORD attrs=GetFileAttributesW(path.c_str());if(attrs==INVALID_FILE_ATTRIBUTES){++data->skipped;it.disable_recursion_pending();}else{bool directory=(attrs&FILE_ATTRIBUTE_DIRECTORY)!=0;if(directory&&(attrs&FILE_ATTRIBUTE_REPARSE_POINT))it.disable_recursion_pending();if(it.depth()>=64){it.disable_recursion_pending();++data->skipped;}auto depth=size_t(it.depth());if(depth>=parents.size()){++data->skipped;it.disable_recursion_pending();}else if(!append(*data,std::move(name),parents[depth],directory,false,bytes))break;else if(directory){if(parents.size()<=depth+1)parents.resize(depth+2);parents[depth+1]=uint32_t(data->entries.size()-1);}}it.increment(ec);if(ec){++data->skipped;ec.clear();}if(++visited%256==0){std::unique_lock lock(mutex);wake.wait_for(lock,std::chrono::milliseconds(8),[&]{return stop||!current(r);});}}
                if(!current(r)||data->limited)break;}
            if(current(r)){write(*data,file,r);{std::lock_guard lock(mutex);if(current(r))building=false;}publish(data,r);}
        }catch(...){std::function<void()> callback;{std::lock_guard lock(mutex);if(current(r)){error=L"Index could not finish. Press Ctrl+R to retry.";building=false;callback=changed;}}if(callback)callback();}
    }SetThreadPriority(GetCurrentThread(),THREAD_MODE_BACKGROUND_END);}
public:
    explicit LocalIndex(std::function<void()> notify={}):changed(std::move(notify)),worker([this]{run();}){}
    ~LocalIndex(){{std::lock_guard lock(mutex);stop=true;++revision;}wake.notify_one();worker.join();}
    static std::vector<std::wstring> locations(unsigned scope){std::vector<std::wstring> out;if(scope==1){wchar_t drives[256]{};GetLogicalDriveStringsW(256,drives);for(auto p=drives;*p;p+=wcslen(p)+1)if(GetDriveTypeW(p)==DRIVE_FIXED)out.emplace_back(p);}else{for(auto id:{FOLDERID_Desktop,FOLDERID_Documents,FOLDERID_Downloads,FOLDERID_Pictures,FOLDERID_Music,FOLDERID_Videos}){PWSTR path=nullptr;if(SUCCEEDED(SHGetKnownFolderPath(id,KF_FLAG_DONT_VERIFY,nullptr,&path))){std::wstring value(path);CoTaskMemFree(path);if(value.starts_with(L"\\\\"))continue;bool nested=false;auto key=fold(value)+L"\\";for(auto& old:out)if(key.starts_with(fold(old)+L"\\"))nested=true;if(!nested){std::erase_if(out,[&](auto& old){return (fold(old)+L"\\").starts_with(key);});out.push_back(std::move(value));}}}}return out;}
    static std::filesystem::path cacheFile(unsigned scope){PWSTR path=nullptr;if(FAILED(SHGetKnownFolderPath(FOLDERID_LocalAppData,0,nullptr,&path)))return {};std::filesystem::path result=std::filesystem::path(path)/L"DelightIsland"/(scope?L"search-local-drives.v1":L"search-personal.v1");CoTaskMemFree(path);return result;}
    void configure(bool on,std::vector<std::wstring> locations={},std::filesystem::path file={}){std::lock_guard lock(mutex);if(enabled==on&&roots==locations&&cache==file)return;++revision;enabled=on;roots=std::move(locations);cache=std::move(file);snapshot.reset();requested=0;building=false;pending=!on;error.clear();wake.notify_one();}
    void refresh(bool force=false){std::lock_guard lock(mutex);if(!enabled||building||pending)return;auto now=GetTickCount64();if(!force&&requested&&now-requested<120000)return;requested=now;forced=force;pending=true;wake.notify_one();}
    std::vector<Result> query(const std::wstring& query,unsigned expected,const std::atomic<unsigned>& latest,std::wstring& status){refresh();std::shared_ptr<const Snapshot> data;{std::lock_guard lock(mutex);data=snapshot;status=error.empty()?L"Floatlet index: "+std::to_wstring(data?data->entries.size():0)+L" items"+(building||pending?L". Updating...":L". Ctrl+R to refresh."):error;if(data&&data->limited)status+=L" Index full: some files missing. Use Everything for larger collections.";if(data&&data->skipped)status+=L" Some locations unavailable.";}std::vector<Result> results;if(!data)return results;auto parts=tokens(query);if(parts.empty())return results;for(uint32_t i=0;i<data->entries.size();++i){if(expected!=latest.load())return {};auto& e=data->entries[i];if(e.root)continue;bool matches=true;for(auto& token:parts){bool found=false;for(auto p=i;p!=NoParent;p=data->entries[p].parent)if(data->entries[p].lower.find(token)!=std::wstring::npos){found=true;break;}if(!found){matches=false;break;}}if(!matches)continue;Result r;r.target=fullPath(*data,i);r.id=r.target;r.title=e.name;auto split=r.target.find_last_of(L"\\/");r.detail=r.target.substr(0,split);r.kind=e.directory?Kind::Folder:Kind::File;r.score=rank(r,query,false);if(r.score)results.push_back(std::move(r));if(results.size()>=160)sort(results);}sort(results);std::erase_if(results,[](auto& r){return GetFileAttributesW(r.target.c_str())==INVALID_FILE_ATTRIBUTES;});return results;}
};
}
